name: SAST - test code with SonarQube sonarcloud.io

on:
  push:
    branches:
      - main
      - master
      - develop
      - release/*
      - feature/*
      - hotfix/*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pytest-cov selenium playwright

    - name: SAST Scan - Sonarcloud.io - check for code vulnerabilities
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
